### PR TITLE
chore: new repo banner

### PR DESCRIPTION
**Pull request by ImLunaHey**
- new design
- light/dark mode
- mobile support

### CODE REVIEW

**Comment by lukasmalkmus** [comment]
GH preview isn't showing it properly. Any way you can share a screenshot or do we have it already implemented in another repository of ours?

**Comment by ImLunaHey** [comment]
https://github.com/axiomhq/axiom-go/tree/luna/new-banner does this not work? 🤔

**Comment by lukasmalkmus** [comment]
Oh, the first one works. I'm just getting old :D 

Thanks 🙌

**Review by lukasmalkmus — APPROVED** [review]
🙌 🎉

**Pull request merged**
